### ISSUE TITLE
Hyperlinks not opening

### ISSUE THREAD

**Issue by AreJay-Smith** [chrisknepper/android-messages-desktop#1]
Hey man! Thanks for making this into an electron app! This is a complete life saver when toggling between apps on MacOS rather than just having a Chrome tab open.

I was playing around and realized that hyperlinks won't open through the app. Not a big deal, but maybe something to check out whenever you get access?

Anyway, thanks again! This is awesome!

**Comment by Soleedus** [comment]
The issue appears on Win 10 and Debian 9.

**Comment by chrisknepper** [comment]
@AreJay-Smith and @Soleedus Thank you for both being users of my app!

I think I can fix this. Just to be clear, is the behavior you're looking for clicking a hyperlink, such as in a text message (like in this screenshot), to open in your standard browser?

<img width="1212" alt="screen shot 2018-06-24 at 4 34 09 pm" src="https://user-images.githubusercontent.com/4976096/41823356-b2aea64c-77cc-11e8-86ed-dd2a53e10289.png">

**Comment by Soleedus** [comment]
Yeah. Don't open it in the Electron app.

**Comment by chrisknepper** [comment]
Alrighty, I think I've fixed this. I made the change as a pull request to make the code changes extra transparent: https://github.com/chrisknepper/android-messages-desktop/pull/2/files

**Comment by chrisknepper** [comment]
Aaaand release is published. If you close the app and re-open it, within a minute you should get a notification about the update and it should automatically download and install...I'd give it a minute or two to be sure. Then just close and open the app again. Version 0.0.4 is what you're looking for.

Let me know if you still have trouble opening links!

<img width="512" alt="screen shot 2018-06-24 at 5 17 47 pm" src="https://user-images.githubusercontent.com/4976096/41823698-9614d1d6-77d2-11e8-95b9-3455d454f065.png">

**Comment by AreJay-Smith** [comment]
Awesome! Works perfect!

**Comment by innesst** [comment]
Some people send web addresses without http, and so no link is created. Is there a way to make anything with a period and no spaces clickable? Or maybe for security, just with a .com ?
