### ISSUE TITLE
Ubuntu 18.10 Issues

### ISSUE THREAD

**Issue by Dafnik** [chrisknepper/android-messages-desktop#100]
Android Messages is not starting on Ubuntu 18.10. I tried the AppImage and the .deb file. This is the response I'm getting if I launch it via the console.
`Segmentation fault (core dumped)`

**Comment by larivierec** [comment]
I have never really participated in a project, but from what I can see after compiling is it creates an AppImage file. I've seen this with Qt.

Going to have to investigate further

**Comment by Dafnik** [comment]
For Ubuntu 18.10 Users who have this issue, here is a compiled AppImage with the fix.
Thank you @larivierec for the bug fix.
[android-messages.AppImage](https://www.file-upload.net/download-13368387/android-messages-desktop.AppImage.html)

**Comment by Dafnik** [comment]
Fixed
