### ISSUE TITLE
Icon is improperly scaled and tiled in linux tray

### ISSUE THREAD

**Issue by JustEnoughDucks** [chrisknepper/android-messages-desktop#102]
In my XFCE both Linux Mint 19 and Arch Linux.
Mint: x86_64 Linux 4.15.0-38-generic 
Arch: x86_64 Linux 4.18.16-ARCH

The 
![Icon tray](https://user-images.githubusercontent.com/17035587/47814966-10c5f900-dd1d-11e8-9b80-3c3e0e6e2b16.png) icon is incorrectly sized and tiled. It becomes the correct size and untitled only if the panel is 21 pixels or under.

I'm not sure if this is just a 20px image that isn't scaled right or what.

**Comment by warmsweater** [comment]
Having this issue too, using LXDE + Debian.

**Comment by yochananmarqos** [comment]
This no longer happens to me. It may have either been due to a Cinnamon or Electron update, not sure which.

Manjaro Linux
Cinnamon 4.0.5
Electron 3.0.10

**Comment by warmsweater** [comment]
It's bizarre because if put the tile in my Application Launch Bar, that icon seems to be unaffected by it.
![screenshot from 2018-12-20 01-48-09](https://user-images.githubusercontent.com/45935087/50268577-520f8680-03f9-11e9-9620-7ce9a6ae0baf.png)

**Comment by JustEnoughDucks** [comment]
Closing as stale
