### ISSUE TITLE
[Feature Request] Automatic Launch

### ISSUE THREAD

**Issue by Hayholten** [chrisknepper/android-messages-desktop#115]
Hi thre !

First of all, great job for this Desktop version and sorry for my English (I'm French).

Well, is there a way to get an option in the bar menu to set the soft launched at startup on windows ?

Thanks a lot !!

**Comment by innesst** [comment]
If this feature is not implemented, you can put a shortcut here:
shell:startup

**Comment by Hayholten** [comment]
Great ! I solved my problem ;)
