### ISSUE TITLE
Focus on tab switch

### ISSUE THREAD

**Issue by chrisgoffinet** [chrisknepper/android-messages-desktop#12]
If having a conversation with someone with Android Messages, and you Tab to another window and then back, it would be very helpful if we could force a focus back to `text message` control, it loses its focus at the moment requiring a click.

**Comment by chrisknepper** [comment]
Ah ha, I can confirm this happening. This will be a tad more involved than the other issues because this involves poking around the `Webview` where Messages for web itself lives, but this is a good first step into interacting with the `Webview`, so I'll definitely look into this.
