### ISSUE TITLE
Disable Enter to Send

### ISSUE THREAD

**Issue by lordofthepotatoes** [chrisknepper/android-messages-desktop#126]
I really hate the pressing enter to send feature, can this be disabled, please?

**Comment by innesst** [comment]
I see this is implemented now. Thanks. Could there be a keyboard shortcut to send when this feature is enabled (e.g. control-enter or shift-enter) - Perhaps combined with a keyboard shortcut to enter a new line instead of send if the feature is not enabled.
Thanks again.
