### ISSUE TITLE
[Feature Request] Additional Minimize to Tray Options

### ISSUE THREAD

**Issue by innesst** [chrisknepper/android-messages-desktop#128]
1) In addition to the close to tray functionality, it would be nice if there was an option to minimize to tray.  

2) Ability to minimize / close to tray by clicking on the icon in the tray. I make a version with nativeizer and it operated in this manner (but it lacked functionality and many features of this excellent app).

3) Auto minimize after a certain number of seconds of inactivity / not being the focus window.

**Comment by chrisknepper** [comment]
Hi @innesst ,

Thank you for your compliments and being a user of the app!

I am assuming you are requesting these for Windows specifically?

For point 1, I actually did have it as minimizing to tray but there were some complaints and the consensus seemed to be to have it close to tray. We could probably make it a configurable option.

For point 2, we should definitely do that.

For point 3, we may be able to do that, though it would definitely have to be an option and we would have to figure out how long the time would be.

**Comment by innesst** [comment]
Hello.

Yes - Windows specifically.

As for #3: I imagined a user interface with a check box to enable auto-minimize, and then a entry field to the right where the user can enter the number of seconds (maybe have 30 auto-populated, but could be set to any number by the user).
