### ISSUE TITLE
Update URL Address

### ISSUE THREAD

**Issue by edwaine** [chrisknepper/android-messages-desktop#147]
From messages.android.com to messages.google.com/web/

**Comment by ajivoin** [comment]
This is already done in #146, we just need @chrisknepper to approve it. :)

**Comment by infinitesteps** [comment]
Please update @chrisknepper

**Comment by rvcjew** [comment]
I also would love this change, love the support so far and thank you to the dev for the hard work to make this useful on the desktop.

**Comment by 0xC** [comment]
Clicking "Sign out" and then re-scanning the QR code resolved the issue for me, and the fix appears to have been permanent.

**Comment by Signal2Noise903** [comment]
Signing out and scanning the QR code again did not work for me. A pop-up message on the phone states: "Something went wrong. Try again in a few minutes."

I have tried multiple times across multiple "few minutes" later, but alas, here I am complaining about it lol.

**Comment by rvcjew** [comment]
> Clicking "Sign out" and then re-scanning the QR code resolved the issue for me, and the fix appears to have been permanent.
> 
> EDIT: Confirmed, it continues to work as expected after closing and reopening the application. Also, THANK YOU @chrisknepper for this amazing application. I find it indispensable.

Worked hanks for the tip!

**Comment by 0xC** [comment]
So it works for some but not others, interesting. I should have given some environment details;

I'm on Windows 10, Android Messages 0.9.1. Mobile device is a Pixel 2 XL.

Thinking maybe the code differences between the Windows, Mac and Linux versions might explain why it works for some and not others...

**Comment by Nicabus** [comment]
> Clicking "Sign out" and then re-scanning the QR code resolved the issue for me, and the fix appears to have been permanent.
> 
> EDIT: Confirmed, it continues to work as expected after closing and reopening the application. Also, THANK YOU @chrisknepper for this amazing application. I find it indispensable.

Worked for me as well.

**Comment by whiskeyalpharomeo** [comment]
> Clicking "Sign out" and then re-scanning the QR code resolved the issue for me, and the fix appears to have been permanent.

Did the trick for me.
Windows 10, Android Messages 0.9.1. Mobile device is a Samsung 8 Active.

**Comment by chrisknepper** [comment]
Hey everyone,

Thanks for this issue, the kind words, and for the pull request. When I saw Google was making this change I assumed that both URLs would work for a time.

I'll get to approving and pushing out an update as soon as I can :)

@edwaine @ajivoin @infinitesteps @rvcjew @0xC @Nicabus @whiskeyalpharomeo

**Comment by chrisknepper** [comment]
This is now out as v1.0.0, so versioned because the different URL is definitely a breaking change and you will probably have to authorize with the QR code again (though maybe you won't if you did the workaround described above prior to updating to v1.0.0)

Thanks everyone for reporting, engaging, being a user, and being a part of this!

**Comment by chrisknepper** [comment]
For reference, this was solved via #146, #151, #152, #153, and #157.
