### ISSUE TITLE
Provide the list of shortcuts for emojis

### ISSUE THREAD

**Issue by noook** [chrisknepper/android-messages-desktop#148]
For the moment, there is currently no way to guess what is the string shortcut to use an emoji, for example, `xD` gives  `😆` But I can't figure out how to use `😂`

**Comment by douglasrlee** [comment]
You should be able to use the OS's emoji shortcut command.

Mac: Control + Command + Space
Windows: Windows Key + .

**Comment by noook** [comment]
What I want is not that, I know I can use the Mac Emoji Selector, what I want is to know the cheatsheet for "basic" shortcuts, for example when you write `:D` you get 😃. I want to know the list of the left part (`:D`)

**Comment by innesst** [comment]
That cannot possibly be an issue with this app, but with the underlying OS or the Android Messages website, which this app is simply an interface for.
