### ISSUE TITLE
Google changed the address to messages.google.com/web.

### ISSUE THREAD

**Issue by CryptoSiD** [chrisknepper/android-messages-desktop#150]
Hi,

It look like google changed the address and now it's causing an issue.

![RyNZT3b](https://user-images.githubusercontent.com/7094808/55428556-51899e80-5557-11e9-8153-588b6a9b98b3.png)

**Comment by CryptoSiD** [comment]
Sorry I just noticed #146 and #147. Please close the issue.

**Comment by ajivoin** [comment]
You should be able to close your own issue below the comment box.
