### ISSUE TITLE
javascript error

### ISSUE THREAD

**Issue by jjgalvez** [chrisknepper/android-messages-desktop#156]
I'm on version 0.9.1 on arch and today these errors started popping up. The application seems to function after hitting ok
![Screenshot from 2019-04-05 17-54-07](https://user-images.githubusercontent.com/5430012/55658606-396e8500-57cc-11e9-8ffb-cee2b333f388.png)
![Screenshot from 2019-04-05 17-53-58](https://user-images.githubusercontent.com/5430012/55658607-396e8500-57cc-11e9-9932-6b7ed7c3b441.png)

Sorry for the pictures but I couldn't copy the text

**Comment by jjgalvez** [comment]
sorry looks like a dup is issue 149, you can ignore this one

**Comment by chrisknepper** [comment]
Thanks for reporting @jjgalvez , let's continue discussion in #149 .
