### ISSUE TITLE
"Messages for web has a new URL"

### ISSUE THREAD

**Issue by ScottPierce** [chrisknepper/android-messages-desktop#163]
I'm seeing the following error when I open the app:

![Screen Shot 2019-04-18 at 5 23 47 PM](https://user-images.githubusercontent.com/871169/56392220-d84ca580-61fe-11e9-8cb0-077f09a40c07.png)

**Comment by ajivoin** [comment]
What version are you on? I believe this should be fixed in the latest version.

**Comment by mollieru** [comment]
Using Android Messages on Mojave 10.4 and also having this issue. Clicked 'Check for Updates' -- nothing seems to have happened. Tried quitting and restarting the program a few times. Still no dice.

**Comment by ScottPierce** [comment]
Downloading the newest version and installing over the old version fixes this.
