### ISSUE TITLE
Make the Tray Icon Optional

### ISSUE THREAD

**Issue by ScottPierce** [chrisknepper/android-messages-desktop#164]
<img width="29" alt="Screen Shot 2019-04-19 at 4 27 02 PM" src="https://user-images.githubusercontent.com/871169/56442806-02b26780-62c0-11e9-8cdf-30de30eb7337.png">

My tray is so full of icons already. Please provide a toggle to remove the tray icon for this application, so that it's not mandatory. Most Mac apps with tray icons provide a way to turn them off.

**Comment by chrisknepper** [comment]
Hi @ScottPierce , thanks for being a user! Good news, the app already does provide a toggle to remove the tray icon. On MacOS it's under the Preferences menu:
<img width="541" alt="Screen Shot 2019-04-28 at 6 32 26 PM" src="https://user-images.githubusercontent.com/4976096/56870882-19ee0500-69e4-11e9-9435-9b52b06f6772.png">

**Comment by ScottPierce** [comment]
awesome sauce. Thanks :-)
