### ISSUE TITLE
Does this app support MMS attachments too? 

### ISSUE THREAD

**Issue by mkanet** [chrisknepper/android-messages-desktop#167]
I currently use native Windows 10, "Your Phone" app which handles sending and receiving SMS phone messages very well.  It doesn't have to run in the forground constantly to still receive SMS text messages; since it's a UWP app.  However, it doesn't playback MMS video attachments at all.  It would be worth considering switching to the Android Messages Desktop app if it can handle MMS attachments.

**Comment by innesst** [comment]
Yes - It will send and receive MMS. Click on the photo icon to the right of the text entry box to see the list of file types supported. It also has a built in gif search / sender that send by gif. JPGs display and gifs automatically play. However, videos won't play, at least those sent from iphone. You'll need to download the video to your desktop to play.

**Comment by mkanet** [comment]
Thank you for your time and development effort.

**Comment by chrisknepper** [comment]
Thanks @mkanet and @innesst -- the app does indeed support MMS!
