### ISSUE TITLE
GIF option no longer available

### ISSUE THREAD

**Issue by depma** [chrisknepper/android-messages-desktop#171]
After the most recent update I no longer have the option to send GIF from the desktop app. It used to appear next to the emojis/stickers/etc.

https://imgur.com/88CiBXo

**Comment by gitguys** [comment]
It's still working for me.  What OS are you using?  Which version of AMD are you using?

**Comment by depma** [comment]
https://imgur.com/SOBN1R4

OS: Windows 10 Pro 1809
AMD: 1.0.1

**Comment by chrisknepper** [comment]
@depma that is bizarre but would most likely be something Google is doing on their end. It looks good for me on Mac. Could you try signing in/signing out, uninstalling/reinstalling, and perhaps trying with a different computer? If none of that works, you could try with a different phone/SIM card. I'll take a look on Windows as soon as I can.

**Comment by depma** [comment]
@chrisknepper Very odd, all I did was File > Quit and re-launch and now it's back.

https://imgur.com/Q3NpoE3

**Comment by chrisknepper** [comment]
Glad to hear it @depma! Feel free to open another issue if you have another problem :)
