### ISSUE TITLE
javascript error on Linux

### ISSUE THREAD

**Issue by StarrKiss** [chrisknepper/android-messages-desktop#177]
![image](https://user-images.githubusercontent.com/13007697/57231092-71d9cc80-6fdf-11e9-95b1-84822e89892d.png)
![image](https://user-images.githubusercontent.com/13007697/57231093-71d9cc80-6fdf-11e9-8f4d-aeab4a8357e0.png)

I get this error everytime the app opens. It refuses to continue.

**Comment by franckgaga** [comment]
Yep same error as https://github.com/chrisknepper/android-messages-desktop/issues/149#issue-428257853
It was corrected in version 1.0.0 but came back yesterday in 1.0.1

**Comment by nic0machus** [comment]
Bumping. I am also getting this error for the last week or so. Doesn't seem to effect the behavior or performance of the application.

**Comment by mattdenkers** [comment]
Same error on Ubuntu 19.04 on version 1.0.1. I was able to get rid of the issue by following the steps in [this](https://github.com/chrisknepper/android-messages-desktop/issues/149#issuecomment-480463289) comment.

**Comment by nic0machus** [comment]
Yep, looks like this is a reappearance of this bug from 0.9.1.

https://github.com/chrisknepper/android-messages-desktop/issues/149

**Comment by warmsweater** [comment]
Same issue here, both on Fedora & Debian based distributions.

> Same error on Ubuntu 19.04 on version 1.0.1. I was able to get rid of the issue by following the steps in [this](https://github.com/chrisknepper/android-messages-desktop/issues/149#issuecomment-480463289) comment.

Can't seem to get either of his suggestions to work :\ using the appimage if that helps at all.

**Comment by leviwalton09** [comment]
I'm using the snap image on Fedora 30 and I'm also getting this error

**Comment by chrisknepper** [comment]
This should now be fixed in the latest release, v3.0.0

FYI @leviwalton09, as of v3.0.0 I am also now publishing this to the Snapstore (apparently) so it should be installable from there or from the .snap in the v3.0.0 release here on GitHub.
