### ISSUE TITLE
Feature Request: Add x32/x86 Support For Windows

### ISSUE THREAD

**Issue by willowen100** [chrisknepper/android-messages-desktop#178]
Is there any plans for adding 32 bit support for Windows?

**Comment by chrisknepper** [comment]
Hey @willowen100, thanks for filing this issue! I'll put out the next version (sooner rather than later hopefully) which will include 32-bit support on Windows.

**Comment by willowen100** [comment]
Thank you for doing such an awesome job with this app. I'll look forward to using the 32 bit version.
