### ISSUE TITLE
Spell Check No Longer Working

### ISSUE THREAD

**Issue by vrl2** [chrisknepper/android-messages-desktop#196]
Hello, miss-spelled words are no longer underlined on version 2.0.0 - running Chrome 75.0.3770.142 on MacOS. Will this be permanently fixed at some point?

**Comment by chrisknepper** [comment]
Hey @vrl2 , sorry I have taken so long to respond. This should be fixed as of v3.0.0 which I just released. Please download that or update your current app and give it a try. If it still doesn't work, please feel free to open a new issue.
