### ISSUE TITLE
v3.1.0 not remembering dark theme enabled

### ISSUE THREAD

**Issue by GTR8000** [chrisknepper/android-messages-desktop#217]
v3.1.0 on Win 10 x64 is not remembering the dark theme setting when closing/reopening the program. It keeps defaulting to light theme. Have to toggle the dark theme switch in settings to get back to dark theme. Tried reinstalling the software, same behavior.

**Comment by whoster69** [comment]
I'm having a similar problem.  v3.1.0 will switch from dark to light theme without me doing anything and I have to manually force it to go back to dark mode.  Running Windows 10 x64.

Each time I load it, it is in light mode no matter what I set it to.

Dark mode worked fine before but now is broken.

**Comment by vanowm** [comment]
is your system set to dark theme?

**Comment by whoster69** [comment]
Yes.

**Comment by GTR8000** [comment]
There are two settings for Windows 10: the default Windows mode, and the default App mode. Mine are set to Windows = dark, and App = light.

Note that I've always had them set that way, and Android Messages Desktop always operated in dark mode regardless, as I had the setting within the app set to enable dark mode.

This behavior just started with v3.1.0

**Comment by whoster69** [comment]
I have both set to dark mode.

**Comment by gitguys** [comment]
Not remembering dark mode on Mac either.  The previous version remembered my dark mode setting.  I don't have dark mode for the entire system with my macOS Sierra version but I want Messages to be dark nonetheless.  3.1.0 broke this and I have to toggle dark mode each time I open Messages now.

**Comment by Ness199X** [comment]
You will need to disable "use system dark mode setting" under preferences. Its somewhat confusing since on older versions of OSes that don't have dark modes (like MacOS High Sierra) this results in it defaulting itself to light mode. Disabling that setting will cause it to remember which mode you want.

**Comment by benjaminnyc** [comment]
Same problem. Upon startup, it's in light mode, even though the settings (three dots) are set to dark. You have to turn off dark, then turn it back on to reenable. Then it stays dark until the next restart of the app.

**Comment by ffxsam** [comment]
> You will need to disable "use system dark mode setting" under preferences.

I have no such setting, neither on the desktop version nor on my Pixel 4.

**Comment by gitguys** [comment]
> You will need to disable "use system dark mode setting" under preferences. Its somewhat confusing since on older versions of OSes that don't have dark modes (like MacOS High Sierra) this results in it defaulting itself to light mode. Disabling that setting will cause it to remember which mode you want.

I don't see that setting anywhere in Sierra.  Are you talking about this Messages app's preferences or something else?  Only settings I see in this Messages app is "Dark Theme" with a toggle and the ability to enable and disable the dark theme within the 3 dot menu.
![Screen Shot 2019-12-02 at 2 20 10 PM](https://user-images.githubusercontent.com/11050768/69996250-e1308400-150e-11ea-9f6b-132cb8d01b7a.png)
![Screen Shot 2019-12-02 at 2 19 49 PM](https://user-images.githubusercontent.com/11050768/69996261-e68dce80-150e-11ea-86c3-f7c111c35355.png)

**Comment by benjaminnyc** [comment]
I found it in the Settings menu (press Alt to show menubar). However, it seems to have no effect on the problem. I'm now on today's update 3.1.0-2.

**Comment by ffxsam** [comment]
Aha! I didn't think to even look there. Thanks, that did the trick for me.

<img width="581" alt="image" src="https://user-images.githubusercontent.com/12532733/69998051-1d69e180-151b-11ea-9639-22832a6ad49d.png">

**Comment by benjaminnyc** [comment]
For the record, I am running on Manjaro Linux. I have a system dark theme, but no sure what my setting should be with Linux.

**Comment by gitguys** [comment]
> Aha! I didn't think to even look there. Thanks, that did the trick for me.
> 
> <img alt="image" width="581" src="https://user-images.githubusercontent.com/12532733/69998051-1d69e180-151b-11ea-9639-22832a6ad49d.png">

Worked for me as well in Sierra.

**Comment by chrisknepper** [comment]
Hey all, sorry for this confusion--I put a note that this supersedes the setting in the Google menu in the changelog, but I should have been clearer about un-setting the Google setting. I will add a note to the readme. I'm not sure if it's possible to disable the Google setting from the Electron side.

To be clear, for correct dark/light automatic switching, the Google setting "Dark theme" on desktop should be unchecked and "Use System Dark Mode Setting" under the application settings menu should be checked.

As far as Linux support, Electron seems to support dark/light inheritance from the operating system, but the docs do not seem to mention which (if any) distros/window managers/desktop environments are actually supported.

**Comment by benjaminnyc** [comment]
Thanks @chrisknepper. In Manjaro-Gnome, it seems I need to keep _both_ settings (Google's and yours) on dark theme to have dark theme on relaunch.

**Comment by JigoloPete21** [comment]
> Not remembering dark mode on Mac either. The previous version remembered my dark mode setting. I don't have dark mode for the entire system with my macOS Sierra version but I want Messages to be dark nonetheless. 3.1.0 broke this and I have to toggle dark mode each time I open Messages now.

I can confirm this steps works on OSX High Sierra 10.13.6 perfectly!  Thanks!  Indeed that is VERY confusing.

**Comment by JigoloPete21** [comment]
> You will need to disable "use system dark mode setting" under preferences. Its somewhat confusing since on older versions of OSes that don't have dark modes (like MacOS High Sierra) this results in it defaulting itself to light mode. Disabling that setting will cause it to remember which mode you want.

**Comment by JigoloPete21** [comment]
I can confirm this steps works on OSX High Sierra 10.13.6 perfectly!  Thanks!  Indeed that is VERY confusing.

**Comment by GTR8000** [comment]
This issue seems to have rectified itself.

**Comment by BStenfors9119** [comment]
I am using Linux Mint 19.3 Tricia.

To fix this, I unticked the "Settings" -> "Use System Dark Mode Setting" and now the application itself remembers my dark mode setting so when I restart the app it stays in "Dark Mode".

Glad I finally read through this thread because it was driving me insane, lol.

Thanks for this app by the way, it's a life saver for me after I switched from Hangouts to Messages full time.  

Kudos to the contributors!!
Bryan

**Comment by rvcjew** [comment]
> You will need to disable "use system dark mode setting" under preferences. Its somewhat confusing since on older versions of OSes that don't have dark modes (like MacOS High Sierra) this results in it defaulting itself to light mode. Disabling that setting will cause it to remember which mode you want.

Thanks for this tip, use light mode on apps but not ui.
