### ISSUE TITLE
Mac - Spellcheck Missing

### ISSUE THREAD

**Issue by thatchrismiller** [chrisknepper/android-messages-desktop#23]
It appears that the built-in spellcheck on the Mac version is disabled.

**Comment by chrisknepper** [comment]
Thanks for reporting this!

Do you know if spellcheck works on the standard web version of Messages for web?

**Comment by thatchrismiller** [comment]
I just checked Chrome and Firefox and it's working in both of them.

**Comment by vrl2** [comment]
Same here. Thanks for developing this handy desktop client! Everything works great in the Mac version except spellcheck (which works on the standard web version on Chrome / Firefox).

**Comment by cswartzvi** [comment]
Similar situation on Windows 7: the desktop client spell checker does not work but the standard web version does (new issue?).

**Comment by chrisknepper** [comment]
Hi @cswartzvi , I've created 2 experimental versions of the app with spell-checking. There are 2 prominent spell-checking libraries for Electron, each with advantages and drawbacks. I'll need to experiment with them more but I should be able to release an update with spellchecking sooner rather than later.

**Comment by Lightsout565** [comment]
Just wanted highlight this issue again and see if there was any update from @chrisknepper. This, by far, is the frustrating part of using the app. Not having the red dashed line under misspelled words is a big issue in practice for me since I use the app quite frequently.

**Comment by chrisknepper** [comment]
@vrl2 @Lightsout565 @cswartzvi @thatchrismiller Thank you all for your input on this, this feature is now implemented in v0.8.0 (PR #124 )
