### ISSUE TITLE
Mac shortcuts do not work

### ISSUE THREAD

**Issue by owencraston** [chrisknepper/android-messages-desktop#247]
- the expected behaviour on mac when you press `CMD + w` is that the window will close but this does not happen
- Pressing `CMD + q` does quit the entire app but this isn't ideal since it needs to restart everything.

**Comment by andreyrd** [comment]
As a workaround, you can set up a Keyboard Shortcut in System Preferences:
https://github.com/chrisknepper/android-messages-desktop/pull/227#issuecomment-640094234
