### ISSUE TITLE
No texts visible after update to 3,1.0 Linux

### ISSUE THREAD

**Issue by rymar1** [chrisknepper/android-messages-desktop#290]
The window where the messages are usually displayed is staying blank
![messenger](https://user-images.githubusercontent.com/24767721/161325403-25a159df-1ad8-4801-bbc7-dfa2b81b264c.jpg)

**Comment by infool7** [comment]
I'm having the same problem in the Windows App 

Hmmmm...

**Comment by jl2245** [comment]
same issue with the OSX app.

**Comment by innesst** [comment]
#287

**Comment by rymar1** [comment]
So it seems that this version, although still available via snap, is no longer supported. I switched to the version at #287 and all is working as before.

**Comment by anonymousaga** [comment]
+1 on macos
