### ISSUE TITLE
Strange Windows icon artifacting when pinned to taskbar

### ISSUE THREAD

**Issue by Soleedus** [chrisknepper/android-messages-desktop#3]
The Windows icon for your Electron application has a weird artifact when pinned:
![image](https://user-images.githubusercontent.com/1351381/41824303-26e21ecc-77dc-11e8-9c9e-d9b721be4165.png)

The issue is even visible in your example screenshot:
![image](https://user-images.githubusercontent.com/1351381/41824315-529ea6e8-77dc-11e8-8607-ed8c0e204267.png)

**Comment by chrisknepper** [comment]
Strange, I didn't notice that until now. I'm using [electron-icon-maker](https://github.com/jaretburkett/electron-icon-maker) to generate the Windows .ico from a .png. Wonder if it was a fluke, or if there's an incompatibility between that tool and certain types of png files. I'll take a look into this as soon as i can. Thanks for reporting!

**Comment by spncrhrstn** [comment]
I don't think this is isolated to your app, I have other Electron-based apps that do this too, namely [Google Play Desktop Music Player](https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-).

Here's a similar issue in that repo: [New logo is broken on Windows #3069](https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/issues/3069)

![2018-06-25 09_45_32-](https://user-images.githubusercontent.com/18315081/41860926-1a7b8052-785d-11e8-8115-d61f9bee5f1a.png)

**Comment by chrisknepper** [comment]
It seems to be related to pinning items to the taskbar, and I can also see it happening with GPDMP. I took this video of it (zoom in and you can see how the artifact goes away when the apps are unpinned). I'll post it up on their repo too. Oddly, I've tried 2 different utilities to make the icons. We'll have to spend more time on this. I have a hunch it's the source that gets bundled into the ICO. Old-school is BMP, new-school is PNG, but electron-bundler seems to not like when it gets a PNG-based ICO.

[https://i.imgur.com/pCQ5lTx.gifv](https://i.imgur.com/pCQ5lTx.gifv)

**Comment by chrisknepper** [comment]
Hey all, I believe I have solved this by using a different way to export the icons. The changes are in this pull request: https://github.com/chrisknepper/android-messages-desktop/pull/11/files

The icon appears correctly on my Windows machine now (see screenshot). I'll push an update to 0.0.5 shortly. If, after the update you still have a corrupt icon on Windows, try clearing your Windows icon cache and if that doesn't work, unpinning/re-pinning the program to the taskbar. Please let me know if this fixes or doesn't fix the icon, and I apologize for the icon weirdness as well!
![icon_windows_fixed](https://user-images.githubusercontent.com/4976096/41944065-1408c65e-7974-11e8-9147-d688103cc2e8.png)

**Comment by spncrhrstn** [comment]
Just chiming in to say that it looks like it's been fixed for me, thanks for the update!
