### ISSUE TITLE
no icon in gnome

### ISSUE THREAD

**Issue by jjgalvez** [chrisknepper/android-messages-desktop#33]
I don't get the proper icon in gnome, only a "?"

**Comment by jjgalvez** [comment]
just tested 0.2.0 in ubuntu and still no proper icon in the dock

**Comment by jjgalvez** [comment]
looking through your code it looks like you define an icon for windows but not linux, can you please add an icon for linux as well, 
Thanks

**Comment by jjgalvez** [comment]
added some code in app.js so that there is an icon with linux

**Comment by chrisknepper** [comment]
This is fixed in 0.4.0 thanks to you @jjgalvez !
