### ISSUE TITLE
Mac - cannot save images or open web links

### ISSUE THREAD

**Issue by vrl2** [chrisknepper/android-messages-desktop#38]
In the standard web version of Android Messages for web, I can save pictures that I receive / send by right clicking, then selecting "save image as."  Also, when using the web version, I can click on web links that I receive / send and my browser will automatically navigate to the site.

Neither of these options appear to be available on the Mac version of the Messages Desktop App.

Aside from minor issues, the desktop app works very well. Thanks for your work on this!

**Comment by chrisknepper** [comment]
Hi there @vrl2 , thanks for reporting this!

Clicking links should definitely be working in the latest version, could you tell me which version of the app you're using, which operating system you're using, and your default browser?

As far as saving the images via right-click, this is definitely something I'm working on along with copy/cut/paste via right-click. As a workaround for now, you may be able to save images by clicking and dragging them from the window to a folder on your computer, though I've only tested this on macOS.

**Comment by vrl2** [comment]
Thanks for your prompt response! I just received the 0.3.0 update and the links now work when I click them.

I'm also able to save images by clicking and dragging in MacOS - I'll test it out in Windows.

**Comment by chrisknepper** [comment]
@vrl2 Great to hear. I'm working on an update to add a right-click menu for text, images, and videos as well. Thanks for testing and being a user!
