### ISSUE TITLE
Please add menubar display toggle

### ISSUE THREAD

**Issue by purevertigo** [chrisknepper/android-messages-desktop#44]
I have noticed with 0.30 there is now a mac menubar icon. 
Can you please add a toggle to remove it?
I would like to be able to choose the dock or menubar or both without either/or getting filled up with unnecessary icons.

thanks.

**Comment by mwjburton** [comment]
I'd second that request.

Further to this, your menubar icon does not display at all when the macOS 10.13 "System Preferences / General / Use dark menu bar and Dock" feature is enabled.

I imagine you may need to supply an alt icon which is switched on when the menu bar is in the dark mode .

**Comment by JeffersonBledsoe** [comment]
+1 to this. While in dark mode the icon is invisible until you click on it and the mac blue allows you to see it

**Comment by mwjburton** [comment]
Wonderful, thank so much Chris

**Comment by purevertigo** [comment]
Cheers! Thankyou @chrisknepper
