### ISSUE TITLE
Mac App not refreshing

### ISSUE THREAD

**Issue by purevertigo** [chrisknepper/android-messages-desktop#53]
After a while the mac app loses connection with the phone and doesn't update.

**Comment by chrisknepper** [comment]
Hi @purevertigo and @adrianbj ,

I think this is an issue with the background service which runs on the Android app. I see this as well and it seems to resolve if I Force Close the Messages app on my phone, though sometimes I have to unpair and repair the computer. I'll keep this open a bit more to see if this persists or if it becomes obviously related to the desktop version.
