### ISSUE TITLE
Start in Tray and Enable Tray Icon conflict

### ISSUE THREAD

**Issue by jacob-swenson** [chrisknepper/android-messages-desktop#62]
Having both of these settings enabled causes some undesired (?) behavior. I'm happy to look at it sometime later this week and see if I can come up with something if you'd like.

**Comment by chrisknepper** [comment]
You mean on Linux? What is the behavior?

**Comment by jacob-swenson** [comment]
This is not an issue. It was an artifact of my testing my merge and having already had the Start in Tray set after the update. It shouldn't be an issue for others.

**Comment by chrisknepper** [comment]
Do you mean if you had start in tray already enabled but since tray default to off on Linux, the window was not easy to make visible?

**Comment by jacob-swenson** [comment]
Yeah, that's exactly what happened. I'm looking at it a little closer. It may be good to have linux default to off after checking if start in tray is false?

**Comment by chrisknepper** [comment]
In other words, if tray is turned off, automatically turn off start in tray?
