### ISSUE TITLE
Clicking to Open From System Tray

### ISSUE THREAD

**Issue by lexluthor5** [chrisknepper/android-messages-desktop#64]
On Windows 10, everything else I have in my system tray activates/opens upon a single click except your android messages app.

Could you update it to open with a single click instead of a double click?

**Comment by chrisknepper** [comment]
Hi @lexluthor5 ,

I have seen Windows apps behave both ways, some do a single, some do a double-click.

I understand being used to either a single or a double-click, so I made this into an option for the Windows version of the app. It will default to double-click, but you can set it to single click in the Settings menu.

I just need to do a bit more testing to make sure I didn't break anything--the update should be released tonight.

**Comment by lexluthor5** [comment]
I have 12 icons in my system tray.  10 of them have an action on a single click.  A setting to allow me to open your app with a single click works for me.  Thanks!

**Comment by chrisknepper** [comment]
I just released 0.7.0 which now has single or double-click as an option.
![tray toggle](https://user-images.githubusercontent.com/4976096/43234893-b10e37d8-904c-11e8-847f-63a7c8460a9a.png)
