### ISSUE TITLE
Move "Check for Updates" to Help Menu in Windows

### ISSUE THREAD

**Issue by starcms** [chrisknepper/android-messages-desktop#72]
Check for Updates should belong under the Help menu, not the File menu.  This would make it consistent with the vast majority of Windows programs.  

Sorry if I'm nitpicking here -- it's a wonderful app and it's been maturing extremely fast -- thanks for all the hard work!!

**Comment by ajivoin** [comment]
I'm going to pick up some development work on the project, I'll make this change when I get started!

**Comment by chrisknepper** [comment]
@starcms Out as well in v0.8.0
