### ISSUE TITLE
Feature Request: add spellcheck functionality

### ISSUE THREAD

**Issue by jbforth4** [chrisknepper/android-messages-desktop#74]
As a user I would like to have incorrectly spelled words underlined and offer suggestions to correctly spelled words.

OS: Ubuntu 18.04

**Comment by chrisknepper** [comment]
Hi @jbforth4 , thank you for reporting this! It took a long time, but the app now has spellchecking as of v0.8.0 (#124 )

**Comment by innesst** [comment]
The spell check is great, but it is very difficult to see when using dark mode. Can the color of the underline be lighter when in dark mode for more contrast?
