### ISSUE TITLE
Feature Request : Manually Refresh/Update View

### ISSUE THREAD

**Issue by MrChris79** [chrisknepper/android-messages-desktop#82]
I have noticed from time to time that the android messages webpage inside the GUI app is not up to date with what shows on my phones android messages app (galaxy note 8). If I close and reopen the app on my windows 10 computer it refreshes/updates the view. I would like to request an option to manually refresh/update the webpage view that is shown inside the GUI. :)

~MC

**Comment by ajivoin** [comment]
It isn't released yet, if you clone and build my [develop branch](https://github.com/ajivoin/android-messages-desktop/) you should be able to have this! I haven't had time to test my work lately so I haven't made a pull request for it in this repo.

If you do this and encounter and issues please let me know! Thanks :)

**Comment by ajivoin** [comment]
This feature isn't in a release yet.

**Comment by chrisknepper** [comment]
@ajivoin @SethPoulsen @MrChris79 thank you all very much, this is now out as v0.8.0
