### ISSUE TITLE
Abandoned?

### ISSUE THREAD

**Issue by lexluthor5** [chrisknepper/android-messages-desktop#91]
Has this project been abandoned?

**Comment by jaselzer** [comment]
It does seem that way.

**Comment by ajivoin** [comment]
It seems like it might be. I might try to pick up the project in my fork since I've contributed a bit. I'll say something if I do.

**Comment by MrChris79** [comment]
I doubt its abandoned. However, that's the good thing about opensource projects and github. Projects can be forked by people with new/different ideas of how to improve and expand on it. : ) I have already made it portable so that I can carry it on my thumb drive. : )

**Comment by spamsgood** [comment]
@MrChris79 that's actually a really good idea. Would make using it on campus computers a viable option.

**Comment by MrChris79** [comment]
Im working on releasing my code that I used to make it public but I have a lot of other code in it that is private/not public  My code/script is based on AutoIt Script. When and If I do, I plan on giving credit to the the Author of Android Messages and Google, as my code/script is more or less a wrapper of there code ect which I cannot take credit for.

**Comment by chrisknepper** [comment]
Hey all, not abandoned. @MrChris79's theory was correct. Work will start again soon.
