### ISSUE TITLE
Feature Request: Open links in Chome

### ISSUE THREAD

**Issue by justinmyersm** [chrisknepper/android-messages-desktop#92]
Would it be possible to open links in Chrome instead of another app window? If links open in Chrome, things like YouTube would already be signed in.

**Comment by MrChris79** [comment]
I think it would/should/does open links in whatever your current default web browser are? Is chrome set as your current wen browser? What browser does Android Messages open links in currently?

**Comment by justinmyersm** [comment]
I have attached a screenshot of what opens when I click a link. It does not open in Chrome as you can see below, but a separate messages window.

Windows 10 Pro x64 v1803 OS build 17134.254

![chrome](https://user-images.githubusercontent.com/12924428/45269681-ee6fd780-b45f-11e8-9805-b1f25c79e6df.png)
![chrome2](https://user-images.githubusercontent.com/12924428/45269682-ee6fd780-b45f-11e8-808a-bd04bad3c1d9.png)
![chrome3](https://user-images.githubusercontent.com/12924428/45269714-52929b80-b460-11e8-93dc-4d54b13cc8c6.png)

**Comment by icnocop** [comment]
It looks like you have an older version of Android Messages for Desktop.

Which version do you have?

Try downloading and installing the latest v0.7.0.

**Comment by justinmyersm** [comment]
Downloading 0.7.0 seemed to work. Thank you for your support!

**Comment by icnocop** [comment]
You had the Android Messages for Desktop application installed from [here](https://github.com/Android-Messages-For-Desktop/android-messages-for-desktop) which has a version with 1.1.2, but that is a different project. :wink:
