### ISSUE TITLE
add padding to app icon on mac

### ISSUE THREAD

**Issue by lyramsr** [chrisknepper/android-messages-desktop#99]
it looks far bigger than the other round icons on the dock.

<img width="98" alt="screen shot 2018-10-09 at 12 20 28 pm" src="https://user-images.githubusercontent.com/4719242/46663190-bf16cc80-cbbd-11e8-8f2d-3c4825e2c9f3.png">

**Comment by osum4est** [comment]
I would also appreciate a fix for this!
